version: "2"

services:
  mysql-container:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./resources/mysql:/docker-entrypoint-initdb.d

  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
    - ./resources/rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
    - ./resources/rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  app-container:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8085:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-container
    depends_on:
      - rabbitmq-container
      - mysql-container
